import { Saira_Condensed } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header/Header";

const sairaCondensed = Saira_Condensed({
  subsets: ["latin"],
  weight:"400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sairaCondensed.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
